version: '3.9'

services:
  django-project:
    build: 
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
      
    volumes:
      - .:/app

  postgres-db:
    image: postgres:15.3-alpine3.17
    volumes:
      - ./database:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:

