version: '3.9'

services:
  django:
    build: .
    ports:
      - 8000:8000
      
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3-alpine3.17
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
